version: "3.5"
services:

  joinweb:
    build:
      context: .
    command: /app/docker-compose/scripts/docker_compose_run.sh
    ports:
      - "3001:3001"
    # Make changes done outside the container reflect inside the container without needing a rebuild by mounting a volume.
    volumes:
      - .:/app
    networks:
      - bravendev
    depends_on:
      - joindb
    env_file:
      - docker-compose/.env-docker

  joindb:
    image: postgres:9.3
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - bravendev

# Note all Braven web app docker dev envs use this same network so they can talk to each other.
# E.g. the hostname joinweb will resolve inside the ssoweb container if they are on the same docker network.
networks:
  bravendev:
    name: braven_dev_network

volumes:
  db-data:
