version: "3"
services:

  join:
    build:
      context: .
    command: /app/docker-compose/scripts/run.sh
    ports:
      - "3001:3001"
    networks:
      - frontend
    depends_on:
      - joindb
    environment:
      RACK_ENV: development
      VIRTUAL_HOST: join.docker
      DATABASE_NAME: postgres
      DATABASE_USER: postgres
      DATABASE_PASSWORD:
      DATABASE_URL: joindb

  joindb:
    image: postgres:9.3
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - frontend

networks:
  frontend:

volumes:
  db-data:
