version: "3"
services:

  joinweb:
    build:
      context: .
    ports:
      - "3001:3001"
    # Make changes done outside the container reflect inside the container without needing a rebuild by mounting a volume.
    volumes:
      - .:/app
    networks:
      - frontend
      - rubycas-server_frontend
    depends_on:
      - joindb
    env_file:
      - docker-compose/.env-docker

  joindb:
    image: postgres:9.3
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - frontend

networks:
  frontend:
  rubycas-server_frontend:
    external: true

volumes:
  db-data:
