# PRODUCTION and STAGING aren't required as this file is automatically created in those environments.

development: &default
  adapter: postgresql
  encoding: unicode
  database: ${DATABASE_NAME}
  pool: 5
  username: ${DATABASE_USER}
  password: ${DATABASE_PASSWORD}
  host: ${DATABASE_URL}

test:
  <<: *default
  database: beyondz-platform_test
