
development:
  adapter: postgresql
  encoding: unicode
  database: beyondz-platform_development
  pool: 5
  username: beyondz-platform
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: beyondz-platform_test
  pool: 5
  username: beyondz-platform
  password:
