development:
  secret_key_base: <%= ENV['RAILS_SECRET_TOKEN'] %>
  smtp_server: <%= ENV['SMTP_SERVER'] %>
  smtp_username: <%= ENV['SMTP_USERNAME'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  smtp_override_recipient: <%= ENV['SMTP_OVERRIDE_RECIPIENT'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

test:
  secret_key_base: <%= ENV['RAILS_SECRET_TOKEN'] %>
  smtp_server: <%= ENV['SMTP_SERVER'] %>
  smtp_username: <%= ENV['SMTP_USERNAME'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  smtp_override_recipient: <%= ENV['SMTP_OVERRIDE_RECIPIENT'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

staging:
  secret_key_base: <%= ENV['RAILS_SECRET_TOKEN'] %>
  smtp_server: <%= ENV['SMTP_SERVER'] %>
  smtp_username: <%= ENV['SMTP_USERNAME'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  smtp_override_recipient: <%= ENV['SMTP_OVERRIDE_RECIPIENT'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>

production:
  secret_key_base: <%= ENV['RAILS_SECRET_TOKEN'] %>
  smtp_server: <%= ENV['SMTP_SERVER'] %>
  smtp_username: <%= ENV['SMTP_USERNAME'] %>
  smtp_password: <%= ENV['SMTP_PASSWORD'] %>
  aws_bucket: <%= ENV['AWS_BUCKET'] %>
  aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
  aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>